### ISSUE TITLE
MOTD not correctly showing

### ISSUE THREAD

**Issue by einlichtvogel** [RedCokeDevelopment/MCServerPing#12]
Hey, my MOTD is not showing correctly, it has 2 lines separated with an \n and one is colored the other is not.
Idk if this is a bug or an error at my side but could you take a look at it?

![WhatsApp Image 2021-11-28 at 23 38 14](https://user-images.githubusercontent.com/65811753/143790478-0fdcde7b-ce05-47b0-8b64-be551e77a70b.jpeg)
![WhatsApp Image 2021-11-28 at 23 39 00](https://user-images.githubusercontent.com/65811753/143790480-af733c0a-1471-44d5-b3ca-77d875dcdc35.jpeg)

**Comment by ColaIan** [comment]
Hello, could you please confirm whether you are using our MCServerPing API? We do not provide Bungeecord configuration support here.

**Comment by einlichtvogel** [comment]
Of course, give me a minute.

**Comment by einlichtvogel** [comment]
Here you go, is that enough? :)

<img width="242" alt="Bildschirmfoto 2021-11-29 um 00 59 08" src="https://user-images.githubusercontent.com/65811753/143791610-74f97b25-4561-4810-af3a-b2c449d3c87f.png">
<img width="1198" alt="Bildschirmfoto 2021-11-29 um 00 58 22" src="https://user-images.githubusercontent.com/65811753/143791606-1aca21ed-6078-4095-815e-de1765c65ab1.png">
<img width="757" alt="Bildschirmfoto 2021-11-29 um 00 58 53" src="https://user-images.githubusercontent.com/65811753/143791609-7cf5356a-f9c8-4cc5-8a87-30661de627b5.png"
<img width="966" alt="Bildschirmfoto 2021-11-29 um 01 03 01" src="https://user-images.githubusercontent.com/65811753/143791724-d08143f0-db38-4c95-9646-38ce72a4791c.png">

**Comment by einlichtvogel** [comment]
<img width="966" alt="Bildschirmfoto 2021-11-29 um 01 03 01" src="https://user-images.githubusercontent.com/65811753/143791724-d08143f0-db38-4c95-9646-38ce72a4791c.png">

**Comment by ColaIan** [comment]
> Here you go, is that enough? :)
> 
> <img alt="Bildschirmfoto 2021-11-29 um 00 59 08" width="242" src="https://user-images.githubusercontent.com/65811753/143791610-74f97b25-4561-4810-af3a-b2c449d3c87f.png">
> 
> <img alt="Bildschirmfoto 2021-11-29 um 00 58 22" width="1198" src="https://user-images.githubusercontent.com/65811753/143791606-1aca21ed-6078-4095-815e-de1765c65ab1.png">
> 
> <img alt="Bildschirmfoto 2021-11-29 um 00 58 53" width="757" src="https://user-images.githubusercontent.com/65811753/143791609-7cf5356a-f9c8-4cc5-8a87-30661de627b5.png">

Can I have the JSON output as well? Thanks!

**Comment by einlichtvogel** [comment]
> > Here you go, is that enough? :)
> > <img alt="Bildschirmfoto 2021-11-29 um 00 59 08" width="242" src="https://user-images.githubusercontent.com/65811753/143791610-74f97b25-4561-4810-af3a-b2c449d3c87f.png">
> > <img alt="Bildschirmfoto 2021-11-29 um 00 58 22" width="1198" src="https://user-images.githubusercontent.com/65811753/143791606-1aca21ed-6078-4095-815e-de1765c65ab1.png">
> > <img alt="Bildschirmfoto 2021-11-29 um 00 58 53" width="757" src="https://user-images.githubusercontent.com/65811753/143791609-7cf5356a-f9c8-4cc5-8a87-30661de627b5.png">
> 
> Can I have the JSON output as well? Thanks!

https://just-paste.it/I5YWnaBfpw

**Comment by ColaIan** [comment]
Hm I'm sorry can you explain the issue? such as what you are trying to achieve? since the ProxyPingEvent took 312ms to process message is a bungeecord message saying the bungeecord server took longer than expected to respond to the API

**Comment by einlichtvogel** [comment]
Of course! :)

That's my original MOTD from the Server I am pinging in the server.properties:
<img width="436" alt="Bildschirmfoto 2021-11-29 um 01 28 02" src="https://user-images.githubusercontent.com/65811753/143792647-6bbc551b-175c-424b-9b76-18dddffa87e8.png">

raw: Der offizielle Minecraft Server von\:\u00A7r\n   \u00A7e>\u00A76> \u00A73\u00A7nHoferlandstrikesback\u00A7r \u00A76<\u00A7e<

The problem is that the top line is not shown.

**Comment by ColaIan** [comment]
> Of course! :)
> 
> That's my original MOTD from the Server I am pinging in the server.properties: <img alt="Bildschirmfoto 2021-11-29 um 01 28 02" width="436" src="https://user-images.githubusercontent.com/65811753/143792647-6bbc551b-175c-424b-9b76-18dddffa87e8.png">
> 
> raw: Der offizielle Minecraft Server von:\u00A7r\n \u00A7e>\u00A76> \u00A73\u00A7nHoferlandstrikesback\u00A7r \u00A76<\u00A7e<
> 
> The problem is that the top line is not shown.

I don't think it is showing in your Minecraft client's server list either though, have you restarted the Bungeecord server?

**Comment by einlichtvogel** [comment]
These servers are running on 2 different servers, one proxy is hostet on aws, and the subserved is hosted at home. 
The proxy is there to not give my private ip to public. The subserved is only reachable from the AWS hostet proxy so I can't check if it is showing or not, but If I run the subserved on my local machine it shows the full MOTD. The problem is now, that only the lower line of the MOTD is getting caught by the MCServerPinger and not the full, but I need the full version.

**Comment by ColaIan** [comment]
> These servers are running on 2 different servers, one proxy is hostet on aws, and the subserved is hosted at home. The proxy is there to not give my private ip to public. The subserved is only reachable from the AWS hostet proxy so I can't check if it is showing or not, but If I run the subserved on my local machine it shows the full MOTD. The problem is now, that only the lower line of the MOTD is getting caught by the MCServerPinger and not the full, but I need the full version.

However your Minecraft client is not able to catch the first line either?

**Comment by einlichtvogel** [comment]
> > These servers are running on 2 different servers, one proxy is hostet on aws, and the subserved is hosted at home. The proxy is there to not give my private ip to public. The subserved is only reachable from the AWS hostet proxy so I can't check if it is showing or not, but If I run the subserved on my local machine it shows the full MOTD. The problem is now, that only the lower line of the MOTD is getting caught by the MCServerPinger and not the full, but I need the full version.
> 
> However your Minecraft client is not able to catch the first line either?

If I run the server locally on my PC yes it can, but if I connect to the proxy where the Pinger set's the IP it's not, like shown here:
<img width="1198" alt="Bildschirmfoto 2021-11-29 um 00 58 22" src="https://user-images.githubusercontent.com/65811753/143793364-95ad8890-3f89-4c84-bd8e-41a216073100.png">

**Comment by ColaIan** [comment]
> > > These servers are running on 2 different servers, one proxy is hostet on aws, and the subserved is hosted at home. The proxy is there to not give my private ip to public. The subserved is only reachable from the AWS hostet proxy so I can't check if it is showing or not, but If I run the subserved on my local machine it shows the full MOTD. The problem is now, that only the lower line of the MOTD is getting caught by the MCServerPinger and not the full, but I need the full version.
> > 
> > 
> > However your Minecraft client is not able to catch the first line either?
> 
> If I run the server locally on my PC yes it can, but if I connect to the proxy where the Pinger set's the IP it's not, like shown here: <img alt="Bildschirmfoto 2021-11-29 um 00 58 22" width="1198" src="https://user-images.githubusercontent.com/65811753/143793364-95ad8890-3f89-4c84-bd8e-41a216073100.png">

What is the MOTD in your Bungeecord config set to?

**Comment by einlichtvogel** [comment]
I am setting the MOTD in my plugin at the ProxyPingEvent so does not really matter, does it?

<img width="761" alt="Bildschirmfoto 2021-11-29 um 01 48 11" src="https://user-images.githubusercontent.com/65811753/143793473-991ead4b-3d82-4957-89d0-5b8652ab15bb.png">

**Comment by einlichtvogel** [comment]
Here I am pining the subserved and getting the MOTD from it.

**Comment by ColaIan** [comment]
> I am setting the MOTD in my plugin at the ProxyPingEvent so does not really matter, does it?
> 
> <img alt="Bildschirmfoto 2021-11-29 um 01 48 11" width="761" src="https://user-images.githubusercontent.com/65811753/143793473-991ead4b-3d82-4957-89d0-5b8652ab15bb.png">

If it doesn't show up on the Minecraft client either, I guess it matters, since the way the API works is mostly the same as the client (If you are a professional, you can use Wireshark to capture and check the ping packet to see if the server properly responded with what you expected)

**Comment by blockiyt** [comment]
![Uploading Bildschirmfoto 2021-11-29 um 01.54.46.png…]()

**Comment by einlichtvogel** [comment]
I souted the variable at line 153 and that's the output:

{"extra":[{"text":"\n   "},{"color":"yellow","text":">"},{"color":"gold","text":"> "},{"underlined":true,"color":"dark_aqua","text":"Hoferlandstrikesback"},{"text":" "},{"color":"gold","text":"<"},{"color":"yellow","text":"<"}],"text":"Der offizielle Minecraft Server von:"}

and you can see, down there is a text, and that's the first line, so It's getting received but not given to the getMotd() Method.

<img width="761" alt="Bildschirmfoto 2021-11-29 um 01 55 13" src="https://user-images.githubusercontent.com/65811753/143793755-d439f214-de01-45fe-ab4d-5339035bc65a.png">

**Comment by einlichtvogel** [comment]
That's the McServerPing class btw xD

**Comment by ColaIan** [comment]
I think the issue is down to your Bungeecord configuration as the API would only show whatever is shown to your Minecraft client's server list

**Comment by einlichtvogel** [comment]
Okay I finally managed to fix it:

My code:
<img width="761" alt="Bildschirmfoto 2021-11-29 um 02 51 01" src="https://user-images.githubusercontent.com/65811753/143796891-49de7687-be0b-4a86-93bb-952173e0ad0e.png">

The original code
<img width="761" alt="Bildschirmfoto 2021-11-29 um 02 53 49" src="https://user-images.githubusercontent.com/65811753/143796989-1ffe2c1f-8e94-4b17-a162-ac70a05bb4ef.png">

**Comment by einlichtvogel** [comment]
and now I'ts showing up like it should!

<img width="966" alt="Bildschirmfoto 2021-11-29 um 02 51 06" src="https://user-images.githubusercontent.com/65811753/143797046-e72a3807-2d14-4a7c-80de-ecf0007e9192.png">

**Comment by ColaIan** [comment]
Nice! Good to hear that xD
