### ISSUE TITLE
Incorrect handling of "version" property

### ISSUE THREAD

**Issue by binary1024x2** [RedCokeDevelopment/MCServerPing#21]
In guess some cases `version` is a Json object and not a string, so Gson can not perform the cast.

```
Exception in thread "Thread-0" java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsString(JsonElement.java:187)
	at dev.redcoke.mcserverping.MCServerPingResponse.serverPingFromJsonObj(MCServerPingResponse.java:31)
	at dev.redcoke.mcserverping.MCServerPing.getPing(MCServerPing.java:160)
```

**Comment by binary1024x2** [comment]
Link to another discussion on #8 for reference https://github.com/RedCokeDevelopment/MCServerPing/issues/8#issuecomment-1598016376

Also I think this might be because of the version change for `bungeecord-api` I had to do as it looks like Gradle can't locate the version on Maven. Maybe that need to be updated.

![imagen](https://github.com/RedCokeDevelopment/MCServerPing/assets/132934948/647af68f-699d-4bd1-99a5-fdfecb5462b0)

![imagen](https://github.com/RedCokeDevelopment/MCServerPing/assets/132934948/fc71161c-c0d3-4e5f-96aa-559b13c83bd1)

**Comment by RedTeaDev** [comment]
Sorry for the late reply, but after revisiting this issue, I've found the root cause, the issue was releated to how we were handling the version, in newer version (1.19), `version` is now a JsonObject that contains `name` and `protocol`
